services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phanty-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  mailpit:
    image: axllent/mailpit
    ports:
      # Web UI to view emails (e.g., http://localhost:8025)
      - '8025:8025'
      # SMTP server for your application to send mail to
      - '1025:1025'
  adminer:
    image: adminer:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: ["--cluster_mode=emulated", "--lock_on_hashtags"]
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data

volumes:
  postgres_data:
  dragonfly_data: