/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateProjectsRouteImport } from './routes/_private/projects'
import { Route as AuthSetupOrgRouteImport } from './routes/_auth/setup-org'
import { Route as AuthSetupAccountRouteImport } from './routes/_auth/setup-account'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProjectsRoute = PrivateProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthSetupOrgRoute = AuthSetupOrgRouteImport.update({
  id: '/_auth/setup-org',
  path: '/setup-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupAccountRoute = AuthSetupAccountRouteImport.update({
  id: '/_auth/setup-account',
  path: '/setup-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/login': typeof AuthLoginRoute
  '/setup-account': typeof AuthSetupAccountRoute
  '/setup-org': typeof AuthSetupOrgRoute
  '/projects': typeof PrivateProjectsRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/setup-account': typeof AuthSetupAccountRoute
  '/setup-org': typeof AuthSetupOrgRoute
  '/projects': typeof PrivateProjectsRoute
  '/': typeof PrivateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup-account': typeof AuthSetupAccountRoute
  '/_auth/setup-org': typeof AuthSetupOrgRoute
  '/_private/projects': typeof PrivateProjectsRoute
  '/_private/': typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/setup-account' | '/setup-org' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/setup-account' | '/setup-org' | '/projects' | '/'
  id:
    | '__root__'
    | '/_private'
    | '/_auth/login'
    | '/_auth/setup-account'
    | '/_auth/setup-org'
    | '/_private/projects'
    | '/_private/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupAccountRoute: typeof AuthSetupAccountRoute
  AuthSetupOrgRoute: typeof AuthSetupOrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/projects': {
      id: '/_private/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PrivateProjectsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/setup-org': {
      id: '/_auth/setup-org'
      path: '/setup-org'
      fullPath: '/setup-org'
      preLoaderRoute: typeof AuthSetupOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup-account': {
      id: '/_auth/setup-account'
      path: '/setup-account'
      fullPath: '/setup-account'
      preLoaderRoute: typeof AuthSetupAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateProjectsRoute: typeof PrivateProjectsRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateProjectsRoute: PrivateProjectsRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupAccountRoute: AuthSetupAccountRoute,
  AuthSetupOrgRoute: AuthSetupOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
